[project]
name = "KubiScan"
version = "0.0.1"
requires-python = ">=3.12,<3.13"
dependencies = [
    "kubernetes>=11.0.0",
    "ptable>=0.9.2",
    "requests>=2.32.3",
]

[dependency-groups]
dev = []

[tool.uv]
package = false
